POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "jo@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "d5e1bab2-d8c3-4d43-ae6d-df27e108ae87"
}

###

POST http://localhost:3000/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "de22c84b-43fc-41dd-98df-e824923435d5",
    "account_id_to":  "af6f2274-3007-4f98-8094-f293b343167f",
    "amount": 5000
}
